FROM python:3.5-slim

WORKDIR /app

# Uncomment and add your proxy settings if needed. Otherwise you may not
# be able to connect to pypi.python.org when running the pip install command.
#ENV http_proxy http://myproxy:1234
#ENV https_proxy http://myproxy:1234

RUN mkdir logs
COPY main.py setup.py requirements.txt ./

RUN pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r requirements.txt

COPY eiffelactory eiffelactory
# copying of the config file should be done after the container is built,
# e.g. via bind mounting. Uncomment for dev builds of local containers
# RUN mkdir conf
# COPY conf/eiffelactory.config conf/

CMD ["python3", "main.py"]
